version: 0.2

phases:
  install:
    commands:
      - pip install boto3
  build:
    commands:
      - echo Build started on `date`
      - python zip.py JasperLambda.zip lambda_function.py
      - sh delete-bot.sh
      - sh build-bot.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - test.py
