version: 0.2

phases:
  install:
    commands:
      - pip install boto3
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python HelloWorld.py
      - python test.py
      - aws lex-models put-slot-type --name CompareTest --cli-input-json file://CompareTest_slot.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - test.py
